version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: mongodbuser
    restart: always
    ports:
      - 27011:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
